name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
    
    - name: Install dependencies
      run: |
        poetry install
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
    
    - name: Bump version
      id: bump_version
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        poetry version patch
        git add pyproject.toml
        git commit -m "Bump version to $(poetry version -s)"
        git tag $(poetry version -s)
        git push origin main --tags
    
    - name: Build and Publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry publish --build

    - name: Push changes
      run: |
        git push
